# Generated by Django 2.2.6 on 2019-11-02 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mldemo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_sub_category', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
