# Generated by Django 2.2.6 on 2019-11-02 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mldemo', '0002_projectsubcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('project_image', models.FileField(upload_to='')),
                ('project_demo_link', models.CharField(max_length=250)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('project_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mldemo.ProjectCategory')),
                ('project_sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mldemo.ProjectSubCategory')),
            ],
        ),
    ]
