# Generated by Django 2.2.6 on 2019-11-02 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mldemo', '0003_homepageproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageproject',
            name='project_image',
            field=models.FileField(upload_to='project_image/homepage/%Y/%m/%d/'),
        ),
    ]
