# Generated by Django 2.2.6 on 2019-11-02 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mldemo', '0004_auto_20191102_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageproject',
            name='project_image',
            field=models.ImageField(blank=True, null=True, upload_to='project_image/homepage/%Y/%m/%d/'),
        ),
    ]
