# Generated by Django 2.2.6 on 2019-11-05 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mldemo', '0008_auto_20191105_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervised',
            name='project_short_descr',
            field=models.CharField(max_length=300),
        ),
        migrations.CreateModel(
            name='Unsupervised',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('project_image', models.ImageField(blank=True, null=True, upload_to='project_image/innerpage/%Y/%m/%d/')),
                ('project_demo_link', models.URLField(max_length=250)),
                ('project_short_descr', models.CharField(max_length=300)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('project_sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mldemo.ProjectSubCategory')),
            ],
        ),
    ]
